[project]
name = "damin"
version = "0.1.0"
dependencies = [

]

[project.urls]
Repository = "https://github.com/Arktetra/data-mining.git"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

